server:
  port: 5050
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TD-IDP-yuhua-li/config-service.git
          search-paths:
            - "config"
          force-pull: true
      label: main
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'bus refresh'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka

