server:
  port: 5050
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TD-IDP-yuhua-li/config-service.git
          search-paths:
            - "config-service"
          force-pull: true
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
