spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3308/product?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.qq.com
    username: 872584173@qq.com
    password: nejdukgtpmfdbaia
token:
  key: 79r2ZMxzfrFxYD1
  time: 1800000
image:
  location: src/main/resources/static/img
thumbnail:
  location: src/main/resources/static/thumbnail
mail:
  buy:
    title: "Hey %s, some one can SELL the product which you just want!"
    body: "%s can sell this product: %s, contact this seller directly! Seller email: %s."
  sell:
    title: "Hey %s, some one want to BUY your product!"
    body: "%s want to buy your product: %s, contact this buyer directly! Buyer email: %s."

